### PR TITLE
Update SSD210 pinout info

### PR DESCRIPTION
**Pull request by lightelf76**
Update SSD210 pinout info, based on picture from chinese site

### CODE REVIEW

**Comment by fifteenhex** [comment]
Nice work.
Would you mind linking where you saw this?

**Comment by lightelf76** [comment]
Yes, pictures are from 16RD.com
http://bbs.16rd.com/thread-571097-1-1.html

**Comment by lightelf76** [comment]
And these:
http://bbs.16rd.com/thread-570933-1-1.html

**Comment by fifteenhex** [comment]
Awesome, thank you. :)

**Pull request merged**
